{% set name = "pypugjs" %}
{% set version = "6.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pypugjs-{{ version }}.tar.gz
  sha256: f7ffbf98ae9f323f55671a8a1c70f8a164bd5b659ae53ea600a2a57a1895b87b

build:
  entry_points:
    - pypugjs = pypugjs.convert:convert_file
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - poetry-core
    - pip
  run:
    - python >={{ python_min }}
    - charset-normalizer >=2.1.0,<3.0.0
    - six >=1.15.0,<2.0.0

test:
  imports:
    - pypugjs
  commands:
    - pip check
    - pypugjs --help
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/kakulukia/pypugjs
  summary: PugJS syntax template adapter for Django, Jinja2, Mako and Tornado templates
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - kiwi0fruit
    - mfansler
