travis:
  secure:
    BINSTAR_TOKEN: k+16c3tAx4qgo4T7s0SFAUSUovDEBWEm/Y7NVl2LNU1/7AEkpApP1NtFnUJI0+whw3SfMMq3XWBAJwS18c+mAUQinEMGldrCQepj9epELNJqyhVOJr4KR+PuCXUtygND30VAC/UOvgLNHOIdFkh4jlgzGRgtK8LWg+byu8H42pqbvVFp+VQDxajP89USe/t3eIvJduBm6LfUUnf7j2nzuhEVl6C7+Y6/ezsTNysDxQsLLgV1/X5DuW1/829ppgIhzxvmdllDgPVLjTsGktJsPIQ4WMeKB9HchAi+Jm/GxcKmTzrmJJehuhe/FJT8RFG5FBGfp0YJQX3Fx445L1nruh44RatEDsdwU8bkhrxP5M98b+eUoCK+n3W4dfSVNwCCl+KDPfFBphVP+n+E0Yb56xFTUIotp+3GjXM8mV1cdPoa/lplC/DAXxPVvec38OnCSodTVq8sTKiEhYIdsYZwGEuTAPmsBogQZEsFar1AJt+epvJyaZeV3mKanhA1j1j4O8RXOO5Qc5ejufHIzlg4TO0zzrMHx/7D3Vg+f4Pjnk2utlZtYbXeicrBAG8aiRIepArqiHtOz8eP0YJ0BrSXZxIbcLnuZs6kko5xiMPP6iDs3z16GhJWVl7nk6JU6O7Ws4+eJHqqoBS8iFx64bKo8QL0x1vEVBv30A0Klu/arEg=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
